language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - setup=stable
    - coverage=no

before_script:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi

script:
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit; fi
